### ISSUE TITLE
Doesn't show all the images

### ISSUE THREAD

**Issue by kenorb** [vdsabev/image-downloader#51]
URL: https://imgur.com/a/uCSg1

It only shows first few images, not the rest.

**Comment by vdsabev** [comment]
Thanks for opening an issue! The Imgur website seems to be using [virtual scrolling](https://medium.com/frontend-journeys/how-virtual-infinite-scrolling-works-239f7ee5aa58) to improve performance by reducing the number of images on the page.

For example:
1. There are only 30 images when you open the extension at first
2. Then if you scroll down and open the extension again there are 26 images which are different than the ones before
3. Then if you scroll even further down and open the extension there are 28 images which are also different, etc.

Since the purpose of this extension is to show all images currently on the page and nothing else, handling virtual scrolling is outside its capabilities.
